### ISSUE TITLE
Missing function sample_templated_task_desc_from_traj_data

### ISSUE THREAD

**Issue by aleSuglia** [gistvision/moca#1]
Hi there,

Thanks for releasing your code. I just wanted to let you know that it looks like your version of the file [gen/utils/game_util.py](https://github.com/gistvision/moca/blob/main/gen/utils/game_util.py) doesn't have the function `sample_templated_task_desc_from_traj_data` that is required by the evaluation script. The function can be found in the same file of the original ALFRED codebase:
```
def sample_templated_task_desc_from_traj_data(traj_data):
    pddl_params = traj_data['pddl_params']
    goal_str = traj_data['task_type']
    if pddl_params['object_sliced']:
        goal_str += "_slice"
    template = random.choice(glib.gdict[goal_str]['templates'])
    obj = pddl_params['object_target'].lower()
    recep = pddl_params['parent_target'].lower()
    toggle = pddl_params['toggle_target'].lower()
    mrecep = pddl_params['mrecep_target'].lower()
    filled_in_str = template.format(obj=obj, recep=recep, toggle=toggle, mrecep=mrecep)
    return filled_in_str
```
I have the latest version of your code on Github. Did you have this issue?

**Comment by bhkim94** [comment]
Hi, @aleSuglia

We haven't encountered issues related to ```gen/utils/game_util.py```.
Did you get errors from the evaluation scripts that we put in readme with the game_util.py file?

**Comment by bhkim94** [comment]
Close this issue. Feel free to reopen it if you have anything that you want to discuss.
