### ISSUE TITLE
How are the color swap images generated?

### ISSUE THREAD

**Issue by Gasoonjia** [gistvision/moca#2]
Thanks for your great work.
We want to do similar things (texture swap) to original images via AI2thor, but we found out that the current simulator (version 2.1.0) does not support such function.
So may I ask how you swap color for original images? Could you share the image after swapping the color?
Thank you.

**Comment by bhkim94** [comment]
Hi @Gasoonjia,

We didn't swap colors at the simulator level. Instead, we extracted raw images by following [ALFRED](https://github.com/askforalfred/alfred/tree/master/gen) and swapped the colors of the extracted images.
Unfortunately, we don't have the color-swapped images for now.
This is a simple code to swap the colors that you can refer to using PyTorch. You can try it with any image.
Images below are the result of the color swapping.

```
import torch
from PIL import Image
from torchvision.utils import save_image
from torchvision.transforms.functional import to_tensor

input_image = 'img.png'
output_image = 'out.png'

img = to_tensor(Image.open(input_image))
save_image(img[torch.randperm(3)], output_image)
```

![img](https://user-images.githubusercontent.com/25083932/116655020-4b2fb000-a9c5-11eb-83a9-ed4fd6fca371.png)
![res](https://user-images.githubusercontent.com/25083932/116655025-4d920a00-a9c5-11eb-883d-8d40aa77fad5.png)

**Comment by Gasoonjia** [comment]
I see. Thanks for your reply!
