### ISSUE TITLE
Data no longer available?

### ISSUE THREAD

**Issue by ikb-a** [gistvision/moca#3]
Hi,

First, a big thanks for releasing your data and code! 

Unfortunately, I seem to be having some problems downloading the augmented dataset. I've been trying for the last week or so at different times, but I always get this error message from Google:

![image](https://user-images.githubusercontent.com/16598225/124148812-058f7200-da5e-11eb-80f0-d4fe0c8cf6d0.png)

Would it be possible to make the data available by some other means?

Thanks!

**Comment by bhkim94** [comment]
Hi @ikb-a, sorry for the late reply.

It seems that it happens because our dataset has been downloaded so many times that it gets over a certain threshold, as the message says.
We will address this issue and update the instruction for dataset downloading accordingly.

**Comment by bhkim94** [comment]
Sorry for the huge delayed response.
I have just added a Hugging Face repo for the dataset with augmentation.

Let me close this issue and feel free to reopen this if you have any issues on this.
