### ISSUE TITLE
Pre-trained Model  Release

### ISSUE THREAD

**Issue by yuchenlin** [gistvision/moca#4]
Hi ,

Thank you for your great work! We are wondering if there's a plan for releasing your pre-trained model checkpoints. We are interested in using it for evaluation purposes. Thank you very much!

**Comment by bhkim94** [comment]
Hi @yuchenlin,

Sorry for the huge late reply.
Unfortunately, we do not have such a plan. But I have just added a link to the training data, so you can learn MOCA yourself.
Feel free to reopen this if you have any further questions about this.

Thanks!
