### ISSUE TITLE
Model overfitting

### ISSUE THREAD

**Issue by Yanchuan99** [gistvision/moca#5]
I used the parameter values mentioned in the article to train the model. Why is there an overfitting problem?
Looking forward to your reply.

**Comment by bhkim94** [comment]
Hi @Yanchuan99,

Sorry for the huge late reply.
Can you elaborate on the overfitting problem? What kind of overfitting did you observe?

Let me close this for now as it's too late (sorry!) but please feel free to reopen if you have further questions about this.

Thanks!
