### ISSUE TITLE
Data link not working

### ISSUE THREAD

**Issue by tejas1995** [gistvision/moca#6]
Hello, it appears that the [data link](https://alfred-colorswap.s3.us-east-2.amazonaws.com/json_feat_2.1.0.7z
) in the download_data.sh file no longer works - is there some way we can access this file?

**Comment by bhkim94** [comment]
Hi @tejas1995,

Sorry for the late reply.
I have just added a Hugging Face repo link in README.
Please feel free to reopen this if you have any issues with this.

Thanks!
